weather_path: 'data/weather.db'
query_1: 'SELECT * FROM weather'
air_path: 'data/air_quality.db'
query_2: 'SELECT * FROM air_quality'

preprocessing:
  num_imputation_strategy: 'mean'
  cat_imputation_strategy: 'most_frequent'
  scaling: 'standard'
  label_encode_columns:
    - 'Daily Solar Panel Efficiency'
  one_hot_encode_columns:
    - 'Wind Direction'
    - 'Dew Point Category'

model_training:
  algorithm: 'RandomForestClassifier'

model_fine_tuning:
  algorithm: 'RandomForestClassifier'
  param_grid:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, 30]
