weather_path: 'data/weather.db'
query_1: 'SELECT * FROM weather'
air_path: 'data/air_quality.db'
query_2: 'SELECT * FROM air_quality'

preprocessing:
  num_imputation_strategy: 'mean'
  cat_imputation_strategy: 'most_frequent'
  scaling: 'standard'
  label_encode_columns:
    - 'Daily Solar Panel Efficiency'
  one_hot_encode_columns:
    - 'Wind Direction'
    - 'Dew Point Category'

model_training:
  algorithms: 
    - RandomForestClassifier
    - SVC
    - LogisticRegression
    - MLP

model_fine_tuning:
  RandomForestClassifier:
    param_grid:
      n_estimators: [100, 200, 300, 500]
      max_depth: [10, 20, 30, 50]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      bootstrap: [True, False]
  SVC:
    param_grid:
      C: [0.1, 1, 10, 100]
      kernel: ['linear', 'rbf', 'poly', 'sigmoid']
      gamma: ['scale', 'auto']
      degree: [2, 3, 4]
  LogisticRegression:
    param_grid:
      C: [0.1, 1, 10, 100]
      solver: ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
      penalty: ['l2']
      max_iter: [100, 200, 300, None]
  MLP:
    param_grid:
      hidden_layer_sizes: [[50], [100], [150]]
      activation: ['relu', 'tanh']
      solver: ['adam', 'sgd']
      learning_rate_init: [0.001, 0.01]
      max_iter: [200, 300]
